database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:mem:sample

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create

server:
    registerDefaultExceptionMappers: true

logging:
  level: INFO
  loggers:
    com.bank: DEBUG